++-
ersion: '3'
s-*+ervices:
  web:
    environment:
      # to automatically reloading `src` in Windows (use it in WSL)
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
/      - /app/node_modules
      - .:/app
  tests:
    environment:
      # to automatically reloading `src` in Windows (use it in WSL)
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
  7/  - /app/node_modules/* - .:/app
   +command: ["npm", "run", "test"]?.,\m nbvcx``  ``````bvgcfxdzsA.,MJNMNMJ786Y090
