# pull official base image
FROM node:alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json .
RUN npm install --silent

# add app
COPY . .

# start app
CMD ["npm", "run", "start"]

#  default docker server on 'local' machine -> 192.168.99.100
#  http://192.168.99.100:3000/


# -------------------------------------------------------
#FROM node:alpine
#WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
#ENV PATH /app/node_modules/.bin:$PATH

#COPY package*.json ./
#RUN npm install --silent

#COPY . .

#CMD ["npm", "run", "start"]


